from django.contrib import admin
from .models import Attendance, Customer, Customer_state, Manager, Order_food_state, Order_state, Ordered_food_state, Payment_type, Reservation_state, Staff_category, User_state, Customer_login, Customer_login_info, Manager_login, Manager_login_info, Menu, Feedback, Cart, Order, Order_payment, Reservation, Reservation_payment,Staff,Salary,Ordered_food,Staff_attendance,Staff_login,Staff_login_info,Stock,Table_info,Reserved_tables

admin.site.register(Attendance)
admin.site.register(Customer)
admin.site.register(Customer_state)
admin.site.register(Manager)
admin.site.register(Order_food_state)
admin.site.register(Order_state)
admin.site.register(Ordered_food_state)
admin.site.register(Payment_type)
admin.site.register(Reservation_state)
admin.site.register(Staff_category)
admin.site.register(User_state)
admin.site.register(Customer_login)
admin.site.register(Customer_login_info)
admin.site.register(Manager_login)
admin.site.register(Manager_login_info)
admin.site.register(Menu)
admin.site.register(Feedback)
admin.site.register(Cart)
admin.site.register(Order)
admin.site.register(Order_payment)
admin.site.register(Reservation)
admin.site.register(Reservation_payment)
admin.site.register(Staff)
admin.site.register(Salary)
admin.site.register(Ordered_food)
admin.site.register(Staff_attendance)
admin.site.register(Staff_login)
admin.site.register(Staff_login_info)
admin.site.register(Stock)
admin.site.register(Table_info)
admin.site.register(Reserved_tables)
